name: Fly Deploy
on: 
  push:
  schedule:
    - cron: '0 4 1 * *'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  UUID: ${{ secrets.UUID }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Flyctl set UUID
        uses: superfly/flyctl-actions@master
        with:
          args: "secrets set UUID=${{ secrets.UUID }}"
        continue-on-error: true
      - name: Flyctl deploy app
        uses: superfly/flyctl-actions@master
        with:
          args: "deploy"
      - name: Flyctl set region - hkg(Hong Kong)
        uses: superfly/flyctl-actions@master
        with:
          args: "regions set hkg"
